### ISSUE TITLE
Variables cannot be used as expected values in Citrix Assertion or End Clause

### ISSUE THREAD

**Issue by bartamihai** [Blazemeter/CitrixPlugin#20]

**Comment by pmouawad** [comment]
Hello,
Can you show a test plan you have used ?
Thanks

**Comment by bartamihai** [comment]
Hi,
Maybe the screenshot helps. If not, I can send a simple Test Plan.
![citrixAssertion](https://user-images.githubusercontent.com/5910419/78133384-01be0b80-7427-11ea-986f-5efd65a1d1b7.PNG)

I was expecting this variable to be evaluated because there are certain cases when you have to make assertion on dynamic text. 

The workaround is to set in Citrix Interaction a fixed text for End Clause, use Citrix OCR Extractor to extract from coordinates your dynamic data and then use the Response Assertion for the assertion

**Comment by bartamihai** [comment]
Hi,
Maybe the screenshot helps. If not, I can send a simple Test Plan.

**Comment by pmouawad** [comment]
Yes this is currently not handled by plugin.
Requalifying as improvement.
Thanks for report.
