### ISSUE TITLE
More documentation Required

### ISSUE THREAD

**Issue by aqiftekhar** [Blazemeter/CitrixPlugin#21]
Hi,

Thanks for this plugin. I have installed and configured Versions: 0.5.5 from jmeter plugin. I tried to build this code but somehow found issues when installing in JMeter.

The Downloaded Versions: 0.5.5 is installed successfully. But ICA is not downloading properly. It would be great if you can provide step by step documentation for this plugin.

**Comment by pmouawad** [comment]
Hello,
See those 2 links which contain all steps:

- https://github.com/Blazemeter/CitrixPlugin/blob/master/PRE_REQUISITES.md
- https://github.com/Blazemeter/CitrixPlugin/blob/master/README.md

Anything else needed ?

Regards

**Comment by aqiftekhar** [comment]
I have gone through all these and everything is working as expected now. But ICA is not downloading. I will be thankful to you if you can help me to download ICA as i am not able to do this.

secondly, It would be great if you can provide step by step documentation for How to use this plugin. currently, README contains high level overview. I would like to request you to please provide Step By Step documentation. Thanks. Also your help regarding ICA downloading would be great.

**Comment by pmouawad** [comment]
Check in View Results Tree which step among HTTP steps is failing. It should be in red.
Probably a slight variation in URL parameters.
1) Did you enter the correct host, user, password using the Template , wether site is secured or not ?
2) If yes, second step will be to record using regular JMeter recorder and once it works put the working part in the existing download Test Fragment


Readme contains step by step guide.

**Comment by aqiftekhar** [comment]
Thank you Very much @pmouawad  for your help and response.

I would like to know one more thing. I am using Web Portal of Citrix & Desktop application. Will this plugin work to implement performance testing? also what is Context Path? 
I am sorry , I am new to this, so may need your help to understand this plugin.

**Comment by aqiftekhar** [comment]
> Check in View Results Tree which step among HTTP steps is failing. It should be in red.
> Probably a slight variation in URL parameters.
> 
> 1. Did you enter the correct host, user, password using the Template , wether site is secured or not ?
> 2. If yes, second step will be to record using regular JMeter recorder and once it works put the working part in the existing download Test Fragment
> 
> Readme contains step by step guide.

**Comment by aqiftekhar** [comment]
I am using following details.

Details: I am using following [details ](https://drive.google.com/open?id=1rHHaeDzRObpM5UelD-5jc9NIEvuOn-Cs)to connect to Citrix

Providing following [credentials](https://drive.google.com/open?id=1WqkVNObUsLf2EK6Sqa6_p4PHc3XNLc5Q)


Getting following [errors](https://drive.google.com/open?id=1pmh_zrzf0dlByXoIj4A8TrfnO118cf8F)

Let me know what i am missing . All above details are working as expected for me manually using browser.

**Comment by ANURAG-CHOURASIA-BY** [comment]
@aqiftekhar @pmouawad 
This issue is in closed state but I trying to find final update from @aqiftekhar on this case. I am encountering similar issue in ICA download after providing all required details in template.
error log says "test expected to contain ClientSettings"

![ICA error1](https://user-images.githubusercontent.com/78555059/108946564-b0b19a00-762c-11eb-91a6-d5d90003d3ca.jpg)

Thanks

**Comment by 3dgiordano** [comment]
Hi @ANURAG-CHOURASIA-BY 

The current issue was closed.

Create a new issue with this data provided, so we can review it independently.
