### ISSUE TITLE
ICA file is not downloading

### ISSUE THREAD

**Issue by aqiftekhar** [Blazemeter/CitrixPlugin#22]
I am using following details.

Details: I am using following [details ](https://drive.google.com/open?id=1rHHaeDzRObpM5UelD-5jc9NIEvuOn-Cs)to connect to Citrix

Providing following [credentials](https://drive.google.com/open?id=1WqkVNObUsLf2EK6Sqa6_p4PHc3XNLc5Q)

Getting following [errors](https://drive.google.com/open?id=1pmh_zrzf0dlByXoIj4A8TrfnO118cf8F)

Let me know what i am missing . All above details are working as expected for me manually using browser.
I have also noticed that following information is missing in Download ICA [image](https://drive.google.com/open?id=1FoLnJhiMdDFn8smqss2ixBoswrQunKpZ).

Server Port, Server IP/Name & port.

Also, I need to Launch App from Citrix Portal which is desktop application and need to implement performance testing on this.

Also, If I use HTTPS Recording template using JMeter, scripts work fine but using Blazemetter template i am getting following issues mentioned above in images attached,

**Comment by aqiftekhar** [comment]
I am using Following details.

**User Defined Variables:**
![Credentials](https://user-images.githubusercontent.com/8364171/78148737-a56ee200-744e-11ea-8cd9-20506afb36db.png)

Credentials:
![Login2](https://user-images.githubusercontent.com/8364171/78148845-bfa8c000-744e-11ea-9dfe-1c0bc0828686.png)

After providing these details, I am trying to record as mentioned below in image
![Run](https://user-images.githubusercontent.com/8364171/78149188-229a5700-744f-11ea-87eb-71a3818a02e2.png)

What issue i am facing is

**HP2-0 Request:**
![error1](https://user-images.githubusercontent.com/8364171/78149231-2fb74600-744f-11ea-9b25-5f6de8685025.png)

**HP2-0 Response:**
![Error2](https://user-images.githubusercontent.com/8364171/78149281-3fcf2580-744f-11ea-8f21-50fea408b076.png)

**HP2-1 Request**
![Error3](https://user-images.githubusercontent.com/8364171/78149403-67be8900-744f-11ea-8eb8-f56993fa3140.png)

**HP-2-1 Response**
![Error5](https://user-images.githubusercontent.com/8364171/78149488-7d33b300-744f-11ea-8081-145e3d4c5533.png)

Error I am facing here is :

![Error5](https://user-images.githubusercontent.com/8364171/78149518-8886de80-744f-11ea-954a-11a22d1df548.png)


I think I am missing something. I would be thankful to you if you can help me in this regard
Thanks.

**Comment by pmouawad** [comment]
Hello, 
Can you please for each response also show Response Data in Response tab ?

Thanks

**Comment by aqiftekhar** [comment]
Thanks @pmouawad  Response is also mentioned below in detail

**HP-2-0 Response data (BODY)**

![Response Data 1 Body](https://user-images.githubusercontent.com/8364171/78183301-1c24d300-7481-11ea-92e8-f8a2aec87a29.png)

**HP-2-0 Response data (HEADER)**

![Response Data 1 Header](https://user-images.githubusercontent.com/8364171/78183333-2941c200-7481-11ea-9481-c7b666c1a465.png)

HP-2-1 Data 2 Body
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XDEV_HTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>Citrix Gateway</title>
<link rel="SHORTCUT ICON" href="/vpn/images/AccessGateway.ico" type="image/vnd.microsoft.icon">
<META http-equiv="Content-Type" content="text/html; charset=UTF-8">
<META content=noindex,nofollow,noarchive name=robots>
<link href="/vpn/js/rdx/core/css/rdx.css?v=02d30141fd053d5c3448bf04fbedb8d6" rel="stylesheet" type="text/css"/>
<link href="/logon/themes/Default/css/base.css?v=02d30141fd053d5c3448bf04fbedb8d6" rel="stylesheet" type="text/css" media="screen" />
<link rel="stylesheet" href="/logon/fonts/citrix-fonts.css?v=02d30141fd053d5c3448bf04fbedb8d6" type="text/css">
<link href="/logon/themes/Default/css/custom.css?v=02d30141fd053d5c3448bf04fbedb8d6" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="/vpn/js/rdx.js?v=02d30141fd053d5c3448bf04fbedb8d6"></script>
<script type="text/javascript" src="/vpn/login.js?v=02d30141fd053d5c3448bf04fbedb8d6"></script>
<script type="text/javascript" src="/vpn/js/views.js?v=02d30141fd053d5c3448bf04fbedb8d6"></script>
<script type="text/javascript" src="/vpn/js/gateway_login_view.js?v=02d30141fd053d5c3448bf04fbedb8d6"></script>
<script type="text/javascript" src="/vpn/js/gateway_login_form_view.js?v=02d30141fd053d5c3448bf04fbedb8d6"></script> 
<style type="text/css">
body
{
  display : none;
  visibility: hidden;
}
</style>
<SCRIPT language=JavaScript>
// frame-busting script
function changePage()
{
	if( self == top ) {
  		 document.getElementsByTagName("body")[0].style.display = 'block' ;
		 document.getElementsByTagName("body")[0].style.visibility = 'visible' ;
		 ns_fillName();
	} else {
   		top.location = self.location ;
	}

}
function setFocus(obj)
{
   if (obj != null) {
      obj.focus();
   }
}			
			
//-->
</SCRIPT>
<script type="text/javascript" src="/vpn/resources.js?v=02d30141fd053d5c3448bf04fbedb8d6"></script>
<script type="text/javascript" language="javascript">
var Resources = new ResourceManager("/logon/themes/Default/resources/{lang}", "logon");
var eula = new ResourceManager("/logon/themes/EULA/resources/{lang}","custom_strings");
</script>
<script type="text/javascript" src="/vpn/nsshare.js?v=02d30141fd053d5c3448bf04fbedb8d6"></script>
<META content="MSHTML 6.00.2900.2802" name=GENERATOR>
</head>
<body class="ns_body" id=bodyTag>
<!-- Copyright 2001-2005 Citrix Systems, Inc. All Rights Reserved -->
<NOSCRIPT>
<BR><BR>
<table style="WIDTH: 100%">
<tr>
 	<td align="center">
		<table class="CTXMSAM_LogonFont">
			<tr id="errorMessageRow">
				<td class="glowBoxLeft">&nbsp;</td>                            
				<td class="loginTableMidWidth">
					<div id="feedbackArea">
					<div id="feedbackStyle" class="feedbackStyleError">
					<span id="errorMessageLabel" class="messageStyle">
					JavaScript is either disabled in or not supported by the Web browser.  
					To continue logon, use a Web browser that supports JavaScript or enable JavaScript in your current browser.
					</span>
					</div>
					</div>
				</td>                           
				<td class="glowBoxRight">&nbsp;</td>
			</tr>
		</table>
	</td>
</tr>
</table>

<table style="display:none">
</NOSCRIPT>
<script>
rdx.FRAMEWORK_BASE = "/vpn/js";
rdx.page.add_event_handler(rdx.events.PAGE_LOADED, new rdx.callback(login, login.do_action_on_load));
rdx.page.add_event_handler(rdx.events.PAGE_LOADED, new rdx.callback(function()
{
        randomize();
        resize();
}));
$(window).resize(function(){resize();});
</script>
</body>
</html>
```

**HP-2-1 Response data (HEADER)**

![Response Data 2 Header](https://user-images.githubusercontent.com/8364171/78183755-e2a09780-7481-11ea-8573-21b7bc39f94f.png)


Let me know if anything required,

I will be really thankful to you for your help in this regard. What i feel is action HP-2-0

`POST https://login.abc.com/Citrix/AppstoreWeb//Home/Configuration`

is working as expected but Get HP-2-1 is not sending response Text whereas in have seen <clientSetting>...<\clientSetting> in response  manually after login.

**Comment by pmouawad** [comment]
Hello,
The plugin provides a template for getting ICA file that works with Citrix Portal.
Your case seems a little different but it's just about recording with JMeter and correlating the required ids.

The easiest thing would be to make a recording of the login using jmeter and Recording Template and attach recording.xml that is generated (change login/password in it).
Ensure you name each click with a meaningful name, use Firefox and close any other tab except the one dedicated to Citrix.

There is no issue here, I'll see if I can help

**Comment by aqiftekhar** [comment]
@pmouawad  Thank you very much for your kind help. 

Can you please share any sample ? as i am new to this and i need your help to achieve my goals. 

Thanks

**Comment by aqiftekhar** [comment]
Hi @pmouawad ,

I am waiting for your help to understand how i can use this plugin with JMeter Recording Template to perform load testing of application in citrix

Thanks.

**Comment by aqiftekhar** [comment]
Hi @pmouawad any progress on this issue?

**Comment by pmouawad** [comment]
Hello @aqiftekhar ,

I work in the JMeter (JMeter Core project, JMeter-Plugins, jmeter-maven-plugin) community mainly on my personal time and sponsored sometimes (on JMeter project and some plugins) by my [company](https://ubikloadpack.com).

My time being limited, I am unable to  help everybody on my personal time.
If this subject is important for your company, then you can request for consulting.
We do provide such services.

Thanks
Regards

**Comment by aqiftekhar** [comment]
What a pathetic answer @pmouawad. There was no need to make it opensource if this was suppose to company to company support. I will suggest if you cannot provide support, do not call it opensource at-least.

**Comment by pmouawad** [comment]
Open source means:
- Code is open, you can analyze a bug, modify it , contribute
- Read the manual and you should be able to use it, by the way your question is just plain JMeter and has no relation with Citrix in fact, but whatever

If you can't do it yourself, then ask for help and Professional services is one way, that's how some of OSS contributors live, and they deserve respect.
If you know other ways, go ahead my friend.

It does not mean that OSS contributors are here to do your job for free and "live on love and fresh water"

As a contributor of OSS for 15 years, I am really happy with your note about my "pathetic answer", that's so encouraging and will surely encourage OSS. Thank you and have a nice day.

**Comment by aqiftekhar** [comment]
Thanks for your reply sir, Finally I am able to establish connection and download ICA by creating HTTPS requests. the default template do not work for me. Thanks for your help.
