### ISSUE TITLE
Citrix Recorder and then Application Launcher opens a Windowed Mode connections even if TWIMode=On

### ISSUE THREAD

**Issue by bartamihai** [Blazemeter/CitrixPlugin#23]
Even if the downloaded .ica file used for connection has the option TWIMode=On, which should open a seamless connection, the connection is opened Windowed Mode (I can see in the background the Windows Server the published app is running on)
If I open the same downloaded file manually, the connection is seamless.

**Comment by pmouawad** [comment]
This is intentional, see 
https://github.com/Blazemeter/CitrixPlugin/blob/master/PRE_REQUISITES.md
Search for TWIMode

**Comment by bartamihai** [comment]
Hi,

I understand that TWIMode=Off is for Windowed Mode. My downloaded .ica file has it on ON. 
The same .ica file opened manually opens a seamless connection
If I'm wrong, please correct me.

Thanks a lot

**Comment by pmouawad** [comment]
The plugin intentionally forces this, otherwise replay will be too unstable.
Do you have a problem with this behaviour ?
Thanks for clarification.

**Comment by bartamihai** [comment]
Hi,

Yes, I cannot run the tests with at least 2 users. The second user fails to launch the application.
Manually I am able to launch 2 instances of the app using the same user account, but he connections are seamless.
Also, If I edit the TWIMode in the downloaded files and try to open manually two Windowed connections the second connection will close the first one.  So I thought that this is the behaviour of Windowed connections.

Thanks

**Comment by pmouawad** [comment]
I don't think it's related.
We ran multiple test using TWIMode as required and we had multiple sessions.

How are you trying to run ? 
Do you have 1 login per thread ? or same for different one ?
If using CSV Data Set, ensure you use a different login per thread

**Comment by bartamihai** [comment]
Yes , each thread has it's  own login and different .ica file downloaded. But for both logins I use the same user and password.

**Comment by pmouawad** [comment]
> Yes, each thread has it's own login and different .ica file downloaded. But for both logins, I use the same user and password.

Since you use "same user and password", then it's not correct. Such configuration is not supported by plugin and I don't think it reflects real life simulation.

**Comment by bartamihai** [comment]
Ok, now it's clear. Thanks a lot for your help. Cheers.

**Comment by pmouawad** [comment]
You're welcome. Happy you find this plugin useful.
Your feedback is welcome
