### ISSUE TITLE
Errors noticed when running two 2 vusers on same machine

### ISSUE THREAD

**Issue by vhosurtest** [Blazemeter/CitrixPlugin#24]
I'm trying to record some actions of a Notepad application from Citrix StoreFront.

Everything works fine for a single vuser. The Notepad is launched, all my keystrokes and mouse clicks are replayed seamlessly. However, when I set the number of threads to 2 and run the test in jmeter non-gui mode, I notice that two notepads launch but the actions pass in only one thread.

Does that mean I need to use two machines/LGs to test with 2 threads? Doesn't this plugin support a headless mode? Did I miss any key configuration?

**Comment by aqiftekhar** [comment]
I would like to know how you established your connection? using citrix web app? as i am still facing connectivity issue of downloading ica file. it would be great if you can help me

**Comment by vhosurtest** [comment]
Hi aqiftekhar,

In my case too, the ICA file download failed when I first tried the plugin out of the box. However, the requests that lead up to the ica file download are all plain HTTP(S) requests. So, I performed a network capture using Fiddler (you may use the network tab in Chrome Dev Tools as well) for a Citrix login operation and modified the HTTP samplers in the plugin accordingly. That worked and I was able to move forward. I am now able to test the Notepad XenApp with two Load Generators using JMeter distributed testing but I'm not sure if I can run two JMeter threads from the same Load Generator which is the subject of this issue.

Hope this helps!

**Comment by aqiftekhar** [comment]
For more than one user, either your citrix configuration should allow multiple sessions or you need to create connection with different user and download ica file for respective user.

**Comment by aqiftekhar** [comment]
are you able to resolve this issue?

**Comment by scyentyfyc** [comment]
I too would like to see an answer to this question, as it doesn't seem to be addressed in any of the documentation about this plugin.  Its been since April with no feedback from the maintainers of this project... is this project still active?

**Comment by scyentyfyc** [comment]
Thought I'd leave for others a discovery that I made....  at the conclusion of [this article](https://www.blazemeter.com/blog/new-jmeter-citrix-plugin), in the comments section there is some discussion about this problem with some potential solution feedback.

**Comment by 3dgiordano** [comment]
Hi! @vhosurtest @aqiftekhar @scyentyfyc 

The plugin is alive, we were in an owner transition process and working on the next release that will be available in the next few hours in the plugin-manager.

From now on I will be in charge of the citrix-plugin, responding in the issues section and in the jmeter-plugins forum.

As a general use, everything doubts about the plugin should be done in the jmeter-plugins forum.
https://groups.google.com/forum/embed/#!forum/jmeter-plugins

In case a bug or issue is detected it will be promoted to issue on GitHub.
If you wish, it is possible to report issues directly here, in case it is not really an issue, it will be closed and the issue will be asked to be discussed in the jmeter-plugins forum

You can find the updated documentation related to the new version 0.6.0 https://github.com/Blazemeter/CitrixPlugin/blob/master/README.md

The version 0.6.0 is also available in the releases section of GitHub
https://github.com/Blazemeter/CitrixPlugin/releases/tag/0.6.0
For the update if you are not yet in the plugin-manager, uninstall it and follow the procedure indicated in
https://github.com/Blazemeter/CitrixPlugin/blob/master/SETUP.md#download-citrix-plugin-from-github-releases

@vhosurtest The new version has improvements in the concurrent execution of different users.
You have to make sure to assign a different user in each Thread-Group, and per machine it is possible to run a simulation of 15 to 20 users, it depends a lot on the stability of Citrix Receiver on each machine.
If you need to simulate the users assigning each one to a new Thread-Group, you can use CSV Data Set Config in Sharing Mode
https://www.blazemeter.com/blog/csv-data-set-config-in-sharing-mode-made-easy

Sorry if the version does not make this task easy for those users who have not yet had experience in doing this type of simulation in JMeter.
We will work to see if it is possible to provide in the template a simple way to activate multi-user execution mode with CSV Data Set for this type of simulation. Or provide an example in the documentation how to do it with JMeter.

Also the new version has execution in no-gui mode (previous versions that didn't work)

@aqiftekhar If it's okay with you, try the new version, and report the problem you encounter as a new issue. 

@scyentyfyc 
Maybe the information I provided or the updated documentation I posted helps.
If this is not the case and there are doubts, try the jmeter-plugin forum and you will be answered as soon as possible.

I'm already working on the next version and on improving the documentation and examples.
I will be at your service to help you resolve any issues you encounter with the plugin.

Remember to use the jmeter-plugins forum, you can get feedback and ideas from the community on how to configure or run certain simulations.
And, of course, from now on I will also be here and on the forum to help you with anything related to the plugin.

**Comment by 3dgiordano** [comment]
I'm closing this issue because it has been inactive for a few months.
