### ISSUE TITLE
Citrix Interaction - Parameterization

### ISSUE THREAD

**Issue by aqiftekhar** [Blazemeter/CitrixPlugin#34]
Hi,

I am facing issue when adding text to textbox using parameter

![image](https://user-images.githubusercontent.com/8364171/97783883-6fe4cf80-1bbc-11eb-8738-c3285089dc26.png)

any workarround?

**Comment by 3dgiordano** [comment]
Hello @aqiftekhar 
Thanks for reporting the problem.

It is one of the already identified issues that we are working on.
In the coming weeks we will be a release with changes in the Input Text.

In this new version it will improve the keyboard recording.
You will also be able to write freely in the Input Text and incorporate parameter variables in them.
