### ISSUE TITLE
Citrix Recorder is too slow

### ISSUE THREAD

**Issue by aqiftekhar** [Blazemeter/CitrixPlugin#35]
Hi I am using Citrix recorder. when I run script it works as expected but when i start recording using Citrix Recorder and download ICA, It initiate after 1 minute and there is a gap of more than one min in each https call.

**Comment by aqiftekhar** [comment]
I have also created this issue on Stackoverflow . initially i thought it is Jmeter issue but after doing checks, i came to know that this is Citrix Recorder Issue. https://stackoverflow.com/questions/64647568/jmeter-http-request-slow-response

**Comment by aqiftekhar** [comment]
**Response code:Citrix user not logged before 300 ms** is the issue i am getting because of slow response  as  mentioned below in image

![image](https://user-images.githubusercontent.com/8364171/99702856-27804980-2ab8-11eb-8ca4-a76edfc37bd7.png)

**Comment by aqiftekhar** [comment]
The login to citrix web application started at **22:22:31 PM**

![image](https://user-images.githubusercontent.com/8364171/99703110-8940b380-2ab8-11eb-93c4-2dc1af6cfc9d.png)

and it is **ended at  22:38:17 PM**
![image](https://user-images.githubusercontent.com/8364171/99703198-a2496480-2ab8-11eb-8f9b-91aa107561be.png)

Right after ICA Download, the next call is launch ICA and there is total time difference between them is almost 2 minutes.

ICA Downloaded at **22:36:34 PM**

![image](https://user-images.githubusercontent.com/8364171/99703303-c311ba00-2ab8-11eb-8e00-01fcfd556058.png)

Citrix Application Launcher started at **22:38:17 PM**
![image](https://user-images.githubusercontent.com/8364171/99703389-df155b80-2ab8-11eb-8122-a297ee769557.png)

Would be great if you can tell me that why each call is taking almost 2 minute delay and how i can fix this

Regards

**Comment by 3dgiordano** [comment]
Hi @aqiftekhar 
The response messages indicate a communication problem ending in a timeout.

There is no apparent difference between the version that record and the version that playback, behind use the same JMeter test fragment.

Try enabling more debug information.
https://github.com/Blazemeter/CitrixPlugin/blob/master/DEBUG.md

If possible, share with us the result of a View Results Tree recorded in a file.
We need the files for both the Recording moment and the Playback moment to see if it's possible to identify the differences.

**Comment by 3dgiordano** [comment]
I'm closing this issue because it has been inactive for a few months.
