### ISSUE TITLE
ICAClientAdapter Connection Failed

### ISSUE THREAD

**Issue by aqiftekhar** [Blazemeter/CitrixPlugin#36]
Hi,

My Script was working as expected. Earlier icon was without + Sign i.e. 

Last day i believe due to some change in the Citrix, My application on Citrix has name +Sign Prefix to app name 
![image](https://user-images.githubusercontent.com/8364171/99881163-e152f380-2c39-11eb-824e-9f4cfc37a150.png)

Due to this change, i am facing this issue and a message box to contact administrator.

![image](https://user-images.githubusercontent.com/8364171/99881123-85886a80-2c39-11eb-944b-b45799962626.png)

 My machine has installed following Citrix Reciever

![image](https://user-images.githubusercontent.com/8364171/99881230-5292a680-2c3a-11eb-9b33-c0498e881138.png)

Would be great if you can tell me what cause this connection fail issue.
Thanks

**Comment by aqiftekhar** [comment]
Below is the error message 

`ERROR c.b.j.c.c.w.e.ICAClientAdapter: ConnectFailed - arguments [Last client error:1110=>Unknown client error 1110, Last error:70=>Error connecting to server, session is unavailable]`

**Comment by 3dgiordano** [comment]
Hi @aqiftekhar 

We need more information to know what happens.

Can you send us the JMeter log related to the error generated by the plugin?

If no details appear, try enabling more debugging information and sending us the error mentioned.

You can follow this manual to raise the debug level of JMeter and the plugin.
https://github.com/Blazemeter/CitrixPlugin/blob/master/DEBUG.md

**Comment by 3dgiordano** [comment]
I'm closing this issue because it has been inactive for a few months.
