### ISSUE TITLE
Get Text method is returning exception

### ISSUE THREAD

**Issue by aqiftekhar** [Blazemeter/CitrixPlugin#38]
I am getting following exception when i am trying to get text after selecting any text as shown below in image.

![image](https://user-images.githubusercontent.com/8364171/100681429-7b7f0e00-3395-11eb-9cd5-9a2f7ece2e73.png)

let me know how i can fix this?

**Comment by 3dgiordano** [comment]
Hi @aqiftekhar 

We need more information to know what happens.

Can you send us the JMeter log related to the error generated by the plugin?

If no details appear, try enabling more debugging information and sending us the error mentioned.

You can follow this manual to raise the debug level of JMeter and the plugin.
https://github.com/Blazemeter/CitrixPlugin/blob/master/DEBUG.md

**Comment by 3dgiordano** [comment]
I'm closing this issue because it has been inactive for a few months.
