### ISSUE TITLE
java.io.NotSerializableException when trying to run CitrixPlugin on Remote

### ISSUE THREAD

**Issue by gooflee** [Blazemeter/CitrixPlugin#47]
Enviroment Details:
Windows Server 2012 R2
Jmeter 5.4
citrix-plugin 0.7.3.
AdpoptJDK 11.0.10 (32-bit)
Citrix Workspace 1912

I can run Citrix Plugin Test Plans via the GUI and CLI, but when I try to run the test plan on a remote server, I get the following error:

Error in rconfigure() method java.rmi.MarshalException: error marshalling arguments; nested exception is: 
	java.io.NotSerializableException: com.blazemeter.jmeter.citrix.client.windows.WinCitrixClientFactory

I tried different version of JDK, and previous versions of JMeter but the error still occurs when I try to run the test plan on remote.  Even a new Citrix Test Plan with only a manually added Citrix Element Launcher has the error.
![NotSerializableError](https://user-images.githubusercontent.com/5321995/119561371-14a24680-bd73-11eb-80eb-4463e73d6e9f.PNG)

**Comment by 3dgiordano** [comment]
Hi @gooflee 

Thank you for reporting the bug.

We have identified the error, both in its execution by RMI and in the JMeter graphical interface.
Unfortunately we have not been able to invest in solving it for the latest release, but we will try to fix it as soon as possible.

Regarding the errors in the graphical interface of JMeter, the alternative is to use "Duplicate" or "Move" and not to use "Copy and paste".
JMeter when copying and pasting, there it serializes the object to memory and that causes the failure.

Currently the remote execution that is running is the distributed execution using BlazeMeter's Private Location. If you are a BlazeMeter customer, you can contact support to get the Citrix Private Location solution.

For distributed execution of JMeter via RMI, we will work to fix it asap.

**Comment by XerOpsNL** [comment]
@3dgiordano, do you got an update on solving the java.io.NotSerializableException: com.blazemeter.jmeter.citrix.client.windows.WinCitrixClientFactory error?
